//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcCrudDbFirstLecture1.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        public int id { get; set; }
        public string name { get; set; }
        public string Email { get; set; }
        public string address { get; set; }
        public string contact_number { get; set; }
        public string birthday { get; set; }
        public string gender { get; set; }
    }
}
