//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcCrudDbFirstLecture1.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student
    {
        public int id { get; set; }
        public string name { get; set; }
        public string discription { get; set; }
        public string purches_price { get; set; }
        public string selling_price { get; set; }
        public string quantity { get; set; }
    }
}
